name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Deploy to server
      uses: appleboy/scp-action@master
      if: success()
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: .
        target: ~/noten.theskz.dev
    
    - name: Run code in screen session
      uses: appleboy/ssh-action@master
      if: success()
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          screen -XS noten quit
          screen -dm -S noten-${{ github.run_id }} bash -c "cd ~/noten.theskz.dev && python3 main.py; exec sh"
